name: UWP
# You can add a shield for this workflow to your README using this URL:
# https://img.shields.io/github/workflow/status/user/repo/UWP?

# This entire workflow is based on an article by Sébastien Lachanche, you can find the article here:
# https://www.dotnetapp.com/github-actions-for-uwp-apps-the-good-and-the-bad-and-the-ugly/

on:
  push:
    branches: [main]
    paths-ignore:
      - "**/*.md"
      - "**/*.txt"
      - "**/*.gitignore"
      - "**/LICENSE"
      - "**/.editorconfig"
  pull_request:
    branches: [main]
    paths-ignore:
      - "**/*.md"
      - "**/*.txt"
      - "**/*.gitignore"
      - "**/LICENSE"
      - "**/.editorconfig"

jobs:
  build:
    name: Build
    runs-on: windows-latest

    env:
      SigningCertificate: Genpass4Win_TemporaryKey.pfx
      Solution_Path: Genpass4Win.sln
      UWP_Project_Path: Genpass4Win\Genpass4Win.csproj
      UWP_Project_Directory: .\

    steps:
      # Prepare the VM to build and analyze
      - name: Configure Pagefile
        uses: al-cheb/configure-pagefile-action@v1.2
        with:
          minimum-size: 32GB
          maximum-size: 32GB
          disk-root: "C:"

      # Get the contents of the repository
      - name: Checkout
        uses: actions/checkout@v2

      # Build the project
      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1.1

      - name: Decode the pfx
        run: |
          $pfx_cert_byte = [System.Convert]::FromBase64String("${{ secrets.Base64_Encoded_Pfx }}")
          $currentDirectory = Get-Location
          $certificatePath = Join-Path -Path $currentDirectory -ChildPath $env:UWP_Project_Directory -AdditionalChildPath $env:SigningCertificate
          [IO.File]::WriteAllBytes("$certificatePath", $pfx_cert_byte)

      - name: Build the sideload solution
        run: msbuild $env:Solution_Path /p:Platform=x64 /p:AppxBundle=$env:AppxBundle /p:AppxBundlePlatforms="x64" /p:AppxPackageDir=C:\DeployOutput /p:PackageCertificateKeyFile=$env:SigningCertificate /restore
        env:
          AppxBundle: Always
          BuildMode: StoreUpload
          Configuration: Release

      - name: Remove the .pfx
        run: Remove-Item -Path $env:UWP_Project_Directory/$env:SigningCertificate
